[package]
name = "ml-challenge"
version = "0.1.0"
authors = ["Juan Veliz"]
edition = "2018"

[dependencies]
base64 = "0.12.0"
openssl = "0.10.29"
regex = "1.3.7"
clap = "2.33.0"

[dependencies.rusqlite]
version = "0.23.1"
features = ["bundled"]